/**
 * dns.service.js
 *
 * Regenerates the CoreDNS zone file from the current DB state.
 * Called after every create / update / delete so DNS is always in sync.
 *
 * ENV vars used:
 *   ZONE_FILE_PATH   Path CoreDNS reads  (default /etc/coredns/zones/git-sync.app.db)
 *   BASE_DOMAIN      Your domain         (default git-sync.app)
 *   VPS_IP           Your server's IP    (required)
 */

import fs from 'fs'
import path from 'path'
import { Domain } from '../models/domain.model.js'

const ZONE_FILE = process.env.ZONE_FILE_PATH || '/etc/coredns/zones/git-sync.app.db'
const BASE_DOMAIN = process.env.BASE_DOMAIN || 'git-sync.app'
const VPS_IP = process.env.VPS_IP || '0.0.0.0'


/**
 * Rebuild and write the entire zone file.
 * Uses a serial based on current unix timestamp (seconds) so CoreDNS
 * picks up the reload automatically (reload plugin must be in Corefile).
 */
export async function rebuildZoneFile() {
  try {
    // Fetch every domain that has at least an IPv4 address
    const domains = await Domain.find({ ip: { $ne: null } }).lean()

    const serial = Math.floor(Date.now() / 1000)

    let zone = `; Auto-generated by git-sync.app backend — do not edit manually
$ORIGIN ${BASE_DOMAIN}.
$TTL 60

@   IN  SOA  ns1.${BASE_DOMAIN}. admin.${BASE_DOMAIN}. (
              ${serial} ; serial
              3600      ; refresh
              900       ; retry
              604800    ; expire
              60 )      ; minimum TTL

; Name servers
@   IN  NS   ns1.${BASE_DOMAIN}.

; VPS (ns1) itself
ns1 IN  A    ${VPS_IP}

; ── Customer subdomains ────────────────────────────────────────────────
`

    for (const d of domains) {
      // IPv4
      if (d.ip) {
        zone += `${d.subdomain.padEnd(24)} IN  A     ${d.ip}\n`
      }
      // IPv6 (AAAA record)
      if (d.ipv6) {
        zone += `${d.subdomain.padEnd(24)} IN  AAAA  ${d.ipv6}\n`
      }
    }

    // Make sure parent directory exists (useful in dev / first run)
    const dir = path.dirname(ZONE_FILE)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    // Write atomically: write to a tmp file then rename so CoreDNS never
    // reads a half-written file.
    const tmp = `${ZONE_FILE}.tmp`
    fs.writeFileSync(tmp, zone, 'utf8')
    fs.renameSync(tmp, ZONE_FILE)

    console.log(`[DNS] Zone file rebuilt — ${domains.length} record(s) written.`)
  } catch (err) {
    console.error('[DNS] Failed to rebuild zone file:', err)
    // Don't re-throw — a DNS failure must never crash the API
  }
}